apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-module
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-module
  template:
    metadata:
      labels:
        app: go-module
    spec:
      containers:
      - name: go-module
        image: pedrosilva1/go-project
        ports:
        - name: opened-port
          containerPort: 8085
        env: 
        - name: DB_HOST
          value: "postgres-db" # Nome do Service que expõe o banco
        - name: DB_PORT
          value: "5432" # Porta padrão do PostgreSQL
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
