apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-module
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-module
  template:
    metadata:
      labels:
        app: go-module
    spec:
      containers:
      - name: go-module
        image: pedrosilva1/go-project
        ports:
        - name: opened-port
          containerPort: 8085
